### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /string.split(/: Unterminated group

### ISSUE THREAD

**Issue by kevinepost** [Tuchkata/styles-highlighter#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [styles-highlighter](https://github.com/Tuchkata/styles-highlighter) package 2.3.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /string.split(/: Unterminated group

```
At /Users/Postman/.atom/packages/styles-highlighter/lib/styles-highlighter.coffee:79

SyntaxError: Invalid regular expression: /string.split(/: Unterminated group
    at RegExp (native)
    at Object.markSelection (/packages/styles-highlighter/lib/styles-highlighter.coffee:79:35)
    at Object.markTenthStyle (/packages/styles-highlighter/lib/styles-highlighter.coffee:123:6)
    at /packages/styles-highlighter/lib/styles-highlighter.coffee:41:101)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  6x -2:49.6.0 core:move-left (input.hidden-input)
  6x -2:47 core:move-right (input.hidden-input)
 12x -2:43.9.0 core:move-left (input.hidden-input)
  7x -2:41.2.0 core:backspace (input.hidden-input)
     -2:34.8.0 core:confirm (input.hidden-input)
  2x -1:38.2.0 styles-highlighter:markFirstStyle (input.hidden-input)
     -1:16.3.0 styles-highlighter:markThirdStyle (span.syntax--meta.syntax--paragraph.syntax--text)
     -0:58.2.0 styles-highlighter:markFifthStyle (span.syntax--meta.syntax--paragraph.syntax--text)
     -0:29.7.0 styles-highlighter:markTenthStyle (span.syntax--meta.syntax--paragraph.syntax--text)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-file-icons 0.6.0 
atom-material-syntax 1.0.6 
atom-panda-syntax 0.18.0 
browser-plus 0.0.87 
eval-javascript 1.2.0 
open-in-browser 0.5.2 
Quick-JavaScript 2.2.0 
spacegray-atom-dark-syntax 1.3.2 
styles-highlighter 2.3.0 
```

**Comment by Tuchkata** [comment]
Will take a look at it during the Christmas holiday.
