### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /*something*/: Nothing to repeat

### ISSUE THREAD

**Issue by serialhex** [Tuchkata/styles-highlighter#5]
[Enter steps to reproduce:]

Tried to highlight `*moo*` or really anything else that contains a `*` character in it.  In Common Lisp it is common to have dynamic variables named with "earmuffs" like `*something*`.  So this is something that will *always* fail for me when I want to highlight dynamic variables. :cry: 

Thanks!

Default atom-issue stuff follows...

**Atom**: 1.17.2 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [styles-highlighter](https://github.com/Tuchkata/styles-highlighter) package 2.3.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /*routine*/: Nothing to repeat

```
At /C:/Users/538353-08/.atom/packages/styles-highlighter/lib/styles-highlighter.coffee:215

SyntaxError: Invalid regular expression: /*routine*/: Nothing to repeat
    at RegExp (native)
    at Object.markSelection (/packages/styles-highlighter/lib/styles-highlighter.coffee:79:35)
    at Object.markFirstStyle (/packages/styles-highlighter/lib/styles-highlighter.coffee:96:6)
    at /packages/styles-highlighter/lib/styles-highlighter.coffee:32:101)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.17.2/resources/app/src/atom-environment.js:1306:1)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.17.2/resources/app/src/application-delegate.js:347:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:47 editor:consolidate-selections (input.hidden-input)
     -9:47 core:cancel (input.hidden-input)
     -9:03.0 project-find:show (input.hidden-input)
     -9:01.6.0 editor:move-to-first-character-of-line (input.hidden-input)
     -9:00.5.0 core:confirm (input.hidden-input)
     -5:27.9.0 core:move-left (input.hidden-input)
     -4:08.9.0 project-find:show (input.hidden-input)
     -4:05.6.0 core:confirm (input.hidden-input)
     -2:25.5.0 editor:consolidate-selections (input.hidden-input)
     -2:25.5.0 core:cancel (input.hidden-input)
     -2:08.1.0 project-find:show (input.hidden-input)
     -2:06.3.0 core:confirm (input.hidden-input)
     -2:00.1.0 tree-view:toggle (div.results-view.focusable-panel)
     -1:26.2.0 settings-view:open (input.hidden-input)
  3x -0:32.9.0 styles-highlighter:markFirstStyle (span.syntax--meta.syntax--expression.syntax--common.syntax--lisp)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
advanced-open-file 0.16.6 
atom-language-rust 0.12.1 
atom-slime 2.8.0 
atom-yeoman 0.3.15 
base16-syntax 1.8.0 
coal-graal 0.0.1 
compare-files 0.8.0 
editor-background 1.2.38 
force-tab 0.2.2 
hex 0.6.2 
highlight-selected 0.13.1 
ionide-fake 1.2.2 
ionide-fsharp undefined 
ionide-fsi undefined 
ionide-installer 1.4.0 
ionide-paket 2.2.6 
ionide-webview 1.0.3 
ionide-yeoman 2.0.0 
language-batch 0.4.0 
language-brainfuck 0.2.0 
language-cmake 0.3.0 
language-common-lisp 0.9.5 
language-cuda 0.1.0 
language-diff 0.7.0 
language-lisp 0.2.0 
language-llvm 0.1.1 
language-matlab 0.2.1 
language-patch 1.2.0 
language-powershell 4.0.0 
language-racket 0.4.0 
language-vb 0.1.0-pre1 
linter undefined 
minimap 4.28.2 
minimap-split-diff 0.3.7 
split-diff 1.4.1 
styles-highlighter 2.3.0 
swackets 0.26.0 
tablr 1.8.3 
```

**Comment by Tuchkata** [comment]
Will take a look at it during the Christmas holiday.
